NUMPY

In [ ]:
import numpy as np #np is the alias name

In [ ]:
my_list=[3,4,6,7,9]

In [ ]:
type(my_list)

list

In [ ]:
#converting list into array
arr=np.array(my_list)

In [ ]:
print(arr)

[3 4 6 7 9]


In [ ]:
type(arr) #nd stands for ndimentional and here value of 'n' is 1, 1D array

numpy.ndarray

In [ ]:
#multinested array/2D arrays
my_list_1=[3,4,6,7,9]
my_list_2=[6,7,0,1,9]
my_list_3=[2,5,8,3,4]

arr_new=np.array([my_list_1,my_list_2,my_list_3])

In [ ]:
print(arr_new)

[[3 4 6 7 9]
 [6 7 0 1 9]
 [2 5 8 3 4]]


In [ ]:
type(arr_new) #here value of n is 2, 2D array

numpy.ndarray

In [ ]:
arr_new.shape #here 3 indicates number of rows and 5 indicates number of columns

(3, 5)

In [ ]:
arr_new.reshape(5,3)

array([[3, 4, 6],
       [7, 9, 6],
       [7, 0, 1],
       [9, 2, 5],
       [8, 3, 4]])

In [ ]:
arr_new.reshape(4,5)

ValueError: ignored

In [ ]:
#generating numbers using numpy
np.arange(1,20,1) #here we have a range of 1-20(20 being exclusive),
#and step size of 1 which means uniform difference of '1' throughout

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [ ]:
np.arange(1,20,5) #step size is 5

array([ 1,  6, 11, 16])

In [ ]:
np.linspace(1,20,50) #here 50 indicates the count of numbers between 1-20 range

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [ ]:
np.linspace(1,20,80) #here 80 indicates the count of numbers between 1-20 range

array([ 1.        ,  1.24050633,  1.48101266,  1.72151899,  1.96202532,
        2.20253165,  2.44303797,  2.6835443 ,  2.92405063,  3.16455696,
        3.40506329,  3.64556962,  3.88607595,  4.12658228,  4.36708861,
        4.60759494,  4.84810127,  5.08860759,  5.32911392,  5.56962025,
        5.81012658,  6.05063291,  6.29113924,  6.53164557,  6.7721519 ,
        7.01265823,  7.25316456,  7.49367089,  7.73417722,  7.97468354,
        8.21518987,  8.4556962 ,  8.69620253,  8.93670886,  9.17721519,
        9.41772152,  9.65822785,  9.89873418, 10.13924051, 10.37974684,
       10.62025316, 10.86075949, 11.10126582, 11.34177215, 11.58227848,
       11.82278481, 12.06329114, 12.30379747, 12.5443038 , 12.78481013,
       13.02531646, 13.26582278, 13.50632911, 13.74683544, 13.98734177,
       14.2278481 , 14.46835443, 14.70886076, 14.94936709, 15.18987342,
       15.43037975, 15.67088608, 15.91139241, 16.15189873, 16.39240506,
       16.63291139, 16.87341772, 17.11392405, 17.35443038, 17.59

In [ ]:
#random numbers
np.random.rand(3,5) #here 3 indicates the number of rows and 5 indicates the number of columns
#here by default the range is between 0-1(1 being exclusive)
#everytime we run the code cell, we will get randomly generated numbers

array([[0.63564582, 0.57127133, 0.79043677, 0.66613778, 0.06737044],
       [0.29644409, 0.59039739, 0.59451284, 0.41301158, 0.23834922],
       [0.65598037, 0.86128135, 0.62441604, 0.41736548, 0.33285692]])

In [ ]:
np.random.randint(1,20,4) #here 1-20 is the range(20 being exclusive) and 4 indicates the count of random numbers needed in the range
#everytime we run the code cell, we will get randomly generated numbers

array([ 1, 17, 16, 10])

In [ ]:
np.random.randint(10,20,3)

array([19, 17, 16])

PANDAS

In [2]:
import pandas as pd #here pd is the alias name

In [ ]:
data=pd.read_csv("/content/tips.csv")

In [ ]:
data.head() #head() will show first 5 rows of the dataset bydefault

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
data.head(10) #first 10 rows will be displayed

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4
8       15.04  1.96    Male     No  Sun  Dinner     2
9       14.78  3.23    Male     No  Sun  Dinner     2

In [ ]:
data.tail() #tail() will show last 5 rows of the dataset bydefault

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.tail(15)

total_bill   tip     sex smoker   day    time  size
229       22.12  2.88  Female    Yes   Sat  Dinner     2
230       24.01  2.00    Male    Yes   Sat  Dinner     4
231       15.69  3.00    Male    Yes   Sat  Dinner     3
232       11.61  3.39    Male     No   Sat  Dinner     2
233       10.77  1.47    Male     No   Sat  Dinner     2
234       15.53  3.00    Male    Yes   Sat  Dinner     2
235       10.07  1.25    Male     No   Sat  Dinner     2
236       12.60  1.00    Male    Yes   Sat  Dinner     2
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [ ]:
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [1]:
#dummy dataset
import numpy as np

In [3]:
my_data=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['row1','row2','row3','row4','row5'],columns=['col1','col2','col3','col4'])

In [4]:
print(my_data)

      col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19


In [ ]:
my_data.to_csv("topmentordemo.csv")

In [ ]:
my_data.to_excel("topmentordemo.xlsx")

In [5]:
#slicing in DataFrames using iloc[]
my_data.iloc[0:2,1:3] #before the , slicing in rows and after the , slicing in columns

col2  col3
row1     1     2
row2     5     6

In [6]:
my_data

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19

In [7]:
my_data.iloc[1:3,1:3]

col2  col3
row2     5     6
row3     9    10

In [8]:
my_data.iloc[:,:4]

col1  col2  col3  col4
row1     0     1     2     3
row2     4     5     6     7
row3     8     9    10    11
row4    12    13    14    15
row5    16    17    18    19